### ISSUE TITLE
Equivalent version of ChickenTalon for Victor SPX

### ISSUE THREAD

**Issue by RobinsonZ** [flamingchickens1540/ROOSTER#20]
As it is now the `ChickenTalon` class acts as a replacement for Phoenix's `TalonSRX` class, but not for the `VictorSPX` class. An equivalent wrapper would be nice to have.

**Comment by edelmanjm** [comment]
lmao using victors

**Comment by RobinsonZ** [comment]
We're using SPX's for slightly less than half the motors on the bot

**Comment by edelmanjm** [comment]
wait what which wuns why
