### ISSUE TITLE
Pure time based motion profile regularly undershoots/overshoots

### ISSUE THREAD

**Issue by edelmanjm** [flamingchickens1540/ROOSTER#54]
Title. Time to go back and grab that code from [motion-profiling-fancy](https://github.com/flamingchickens1540/ROOSTER/tree/motion-profiling-fancy).

One possible solution is to simply add margins around the velocity where if it isn't going fast enough it does pure time, but that's kinda eh.

**Comment by RobinsonZ** [comment]
Sounds like a job for Position-PID-With-Velocity-Feed-Forward-Man (i. e. native Talon profiling).

**Comment by edelmanjm** [comment]
but mom that's a massive, massive rewrite with lots of stupid handling. FR tho, do we want to do that?

**Comment by RobinsonZ** [comment]
Not that massive. Sure it would need development, but it's basically 100% boilerplate and maybe 200 LOC max (our generic implementation on Henny was a [250-line file](https://github.com/flamingchickens1540/hensolo-chewbawka-2017/blob/master/AlternativeRobot/src/org/team1540/robot2017/motion/MotionProfile.java) + a [small amount of additional code](https://github.com/flamingchickens1540/hensolo-chewbawka-2017/blob/master/AlternativeRobot/src/org/team1540/robot2017/subsystems/DriveTrain.java#L30) in `DriveTrain`). 

The implementation is stupidly written (Integer state machines? Seriously?) and not integrated into WPILib but we could repackage it as a command that loads a `double[][]` (or an iterable of some custom data class if we want to be all object-oriented) into the motion profile buffer, then executes the profile. It would require some amount of cognitive effort to figure out how CTRE's stuff works but it's just making sense of an (albeit poorly documented) API–no need to figure out our own profile-following algorithms.

**Comment by edelmanjm** [comment]
> buffer
And if you exceed it, you have to start dealing with loading. Okay, sure, it's really big, but that gets real annoying real fast.

**Comment by RobinsonZ** [comment]
Dealing with buffer loading is not too hard with the command framework. In your `execute()` method, just constantly add points to the buffer until it's full or you run out of points. (Maybe do only X points per loop if it becomes a speed issue.) Then, run the motion profile. If you happen to have more than 2048 points they just get added in the next iteration of `execute()`.

Alternatively, we could just make an executive decision that we'll cap profiles at 2048 points. Given that at 10ms per point 2048 points will take you through all of auto with half a second to spare, that wouldn't be too bad. In that case, we'd just have to handle first-time loading and profile execution and could always add buffer handling later.

**Comment by edelmanjm** [comment]
Isn't the dealio with all the weird stuff machines to deal with the buffer loading if it occurs while you're running? I'm having trouble reading the code, so it's quite possible I misinterpreted it.

**Comment by RobinsonZ** [comment]
I think so. CTRE does a full walkthrough of their code in the Motion Profile Reference Manual which is on their website, though that may not help knowing their docs.

**Comment by edelmanjm** [comment]
Alrighty so whenever @RobinsonZ finishes we're deleting the old crap from [org.team1540.base.motionprofiling](https://github.com/flamingchickens1540/ROOSTER/tree/master/src/main/java/org/team1540/base/motionprofiling)

**Comment by RobinsonZ** [comment]
@wangl5 and I have a nice motion profile implementation over in the Pandora repo. It's written tied into the robot code for development speed, but I'll be extracting it after Houston and putting it here.

**Comment by RobinsonZ** [comment]
This got closed on accident, reopening
