### ISSUE TITLE
RunMotionProfiles.isFinished() doesn't work

### ISSUE THREAD

**Issue by edelmanjm** [flamingchickens1540/ROOSTER#62]

**Comment by RobinsonZ** [comment]
This got closed on accident, reopening

**Comment by edelmanjm** [comment]
Wait wasn't this supposed to be closed?

**Comment by RobinsonZ** [comment]
Nope, it was closed on accident when #92 was marked as merged (as all of its commits were merged) despite the bits that closed this issue actually being reverted.
